# YAML file for API prod Deployments and Services
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-managed-disk-prod
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 5Gi
---
# YAML to deploy MongoDB image and allow communication over container port 27017, with a database initialised named "database"
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fyp-mongodb-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment-name: fyp-mongodb-prod
  template:
    metadata:
      labels:
        deployment-name: fyp-mongodb-prod
    spec:
      containers:
        - name: fyp-mongodb-prod
          image: mongo
          env: 
            - name: MONGO_INITDB_DATABASE
              value: database
          ports:
            - containerPort: 27017
          volumeMounts:
          - mountPath: "/data/db"
            name: volume-prod
      volumes:
        - name: volume-prod
          persistentVolumeClaim:
            claimName: azure-managed-disk-prod
---
# YAML to deploy loadbalancer for the MongoDB database mapping incoming port 27017 to target port 27017 for the MongoDB deployment named "fyp-mongodb-prod"
apiVersion: v1
kind: Service
metadata:
  labels:
    service-label: fyp-mongodb-cluster-service-prod
  name: fyp-mongodb-cluster-service-loadbalancer-prod
spec:
  type: LoadBalancer
  ports:
    - name: fyp-mongodb-load-balancer-service-port-prod
      port: 27017
      targetPort: 27017
      protocol: TCP
  selector:
    deployment-name: fyp-mongodb-prod
---
# YAML to deploy latest API image pushed to the Azure Container Repository for API prod images and allow communication over container port 3000
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fyp-api-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment-name: fyp-api-prod
  template:
    metadata:
      labels:
        deployment-name: fyp-api-prod
    spec:
      containers:
      - name: fyp-api-prod
        image: acrfypianh.azurecr.io/fyp-ianh-api-prod
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
---
# YAML to deploy loadbalancer for the API mapping incoming port 3000 to target port 3000 for the API deployment named "fyp-api-prod"
apiVersion: v1
kind: Service
metadata:
  labels:
    service-label: fyp-api-cluster-service-prod
  name: fyp-api-cluster-service-loadbalancer-prod
spec:
  type: LoadBalancer
  ports:
    - name: fyp-api-load-balancer-service-port-prod
      port: 3000
      targetPort: 3000
      protocol: TCP    
  selector:
    deployment-name: fyp-api-prod
---
#  YAML to deploy Horizontal Pod Autoscaler for the API "fyp-api-prod" that will scale the API from 1 to 5 replicas if allocated CPU utilization for a container exceeds 50%
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: fyp-api-prod-hpa
spec:
  maxReplicas: 5 # define max replica count
  minReplicas: 1  # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fyp-api-prod
  targetCPUUtilizationPercentage: 50 # target CPU utilization